#Esse workflow irá buildar um projeto maven utilizando restAssured como base

name: Integration Test (RestAssured)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven and run Test
        run: mvn test -B package --file pom.xml

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: TestNG Report
          path: target/surefire-reports/testng-results.xml